
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ToMImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8001/ws/TigersOfMemphis?wsdl")
public class ToMImplService
    extends Service
{

    private final static URL TOMIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOMIMPLSERVICE_EXCEPTION;
    private final static QName TOMIMPLSERVICE_QNAME = new QName("http://ws/", "ToMImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/ws/TigersOfMemphis?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOMIMPLSERVICE_WSDL_LOCATION = url;
        TOMIMPLSERVICE_EXCEPTION = e;
    }

    public ToMImplService() {
        super(__getWsdlLocation(), TOMIMPLSERVICE_QNAME);
    }

    public ToMImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOMIMPLSERVICE_QNAME, features);
    }

    public ToMImplService(URL wsdlLocation) {
        super(wsdlLocation, TOMIMPLSERVICE_QNAME);
    }

    public ToMImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOMIMPLSERVICE_QNAME, features);
    }

    public ToMImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToMImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ToM
     */
    @WebEndpoint(name = "ToMImplPort")
    public ToM getToMImplPort() {
        return super.getPort(new QName("http://ws/", "ToMImplPort"), ToM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToM
     */
    @WebEndpoint(name = "ToMImplPort")
    public ToM getToMImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ToMImplPort"), ToM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOMIMPLSERVICE_EXCEPTION!= null) {
            throw TOMIMPLSERVICE_EXCEPTION;
        }
        return TOMIMPLSERVICE_WSDL_LOCATION;
    }

}
